code_syntax_highlight = "dracula"
full_screen_fg = "#b9b19c"
full_screen_bg = "#2d2621"
gradient_color = ["#51a2da", "#957fb8"]
file_panel_fg = "#b9b19c"
file_panel_bg = "#2d2621"
file_panel_border = "#5c4f47"
file_panel_border_active = "#51a2da"
file_panel_top_directory_icon = "#dca561"
file_panel_top_path = "#b9b19c"
file_panel_item_selected_fg = "#dca561"
file_panel_item_selected_bg = "#3d3530"
footer_fg = "#b9b19c"
footer_bg = "#2d2621"
footer_border = "#5c4f47"
footer_border_active = "#98bb6c"
sidebar_fg = "#b9b19c"
sidebar_bg = "#2d2621"
sidebar_title = "#7aa89f"
sidebar_border = "#2d2621"
sidebar_border_active = "#98bb6c"
sidebar_item_selected_fg = "#dca561"
sidebar_item_selected_bg = "#3d3530"
sidebar_divider = "#5c4f47"
modal_fg = "#b9b19c"
modal_bg = "#3d3530"
modal_border_active = "#dca561"
modal_cancel_fg = "#2d2621"
modal_cancel_bg = "#cc4a4a"
modal_confirm_fg = "#2d2621"
modal_confirm_bg = "#98bb6c"
help_menu_hotkey = "#51a2da"
help_menu_title = "#dca561"
cursor = "#b35d5d"
correct = "#98bb6c"
error = "#cc4a4a"
hint = "#7aa89f"
cancel = "#cc4a4a"