# --- CLEAN FLAT VIBE (HYPRLOCK) ---

background {
    monitor =
    path = ~/Pictures/newwall.jpg
    # Wenn das Bild fehlt, fällt er auf Deep Blue zurück:
    color = rgb(0d111c)
    
    # Minimaler Blur, genau wie in deiner Sway-Config
    blur_passes = 2
    blur_size = 5
}

# --- UHRZEIT ---
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M:%S')"
    color = rgb(e0e5f5) 
    font_size = 80
    font_family = Nunito Bold
    position = 0, 140
    halign = center
    valign = center
}

# --- DATUM ---
label {
    monitor =
    text = cmd[update:18000000] echo "$(date +'%A, %d. %B')"
    color = rgb(b072d1) # Cyber Purple für einen schönen Akzent
    font_size = 22
    font_family = Nunito Bold
    position = 0, 60
    halign = center
    valign = center
}

# --- PASSWORTFELD (Bleibt wie vorher) ---
input-field {
    monitor =
    size = 350, 50
    outline_thickness = 2
    rounding = 8 
    
    outer_color = rgb(b072d1)
    inner_color = rgb(1a2133)
    font_color = rgb(e0e5f5)
    
    placeholder_text = <i>Passwort...</i>
    fade_on_empty = false
    
    check_color = rgb(f05ca0)
    fail_color = rgb(f05ca0)
    fail_text = <i>Falsch <b>($ATTEMPTS)</b></i>

    position = 0, -50
    halign = center
    valign = center
}