# --- Schriftart ---
font_family      JetBrainsMono Nerd Font Bold
font_size        11.0

# --- Fenster & Transparenz ---
window_padding_width 15
background_opacity 0.92

# --- Cursor ---
cursor_shape block
cursor #b35d5d
cursor_text_color #2d2621
cursor_blink_interval 0.5

# --- Farben ---
background #2d2621
foreground #b9b19c

# Regular colors (0-7)
color0  #3d3530
color1  #cc4a4a
color2  #98bb6c
color3  #dca561
color4  #51a2da
color5  #957fb8
color6  #7aa89f
color7  #b9b19c

# Bright colors (8-15)
color8  #5c4f47
color9  #ff5d5d
color10 #b1e381
color11 #ff9e3b
color12 #73c1ff
color13 #d183e8
color14 #a3d4d5
color15 #f5ebd0

# Optional: Schaltet den nervigen Audio-Bell-Ton aus
enable_audio_bell no
